# Generated by Django 5.2.17 on 2026-09-27 07:41

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0006_chain_rpc_url_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fungible_id', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('usd', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fungible_id', 'day'), name='wallets_unique_price')],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='wallets_entity_tags')],
            },
        ),
        migrations.CreateModel(
            name='KnownAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('kind', models.CharField(choices=[('exchange', 'Exchange'), ('cex_deposit', "Dépôt d'exchange"), ('service', 'Service'), ('bridge', 'Bridge'), ('router', 'Router'), ('mev', 'Bot MEV'), ('stablecoin', 'Stablecoin'), ('wrapped_native', 'Natif wrappé')], max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('source', models.CharField(choices=[('import', 'Import'), ('manual', 'Manuel'), ('auto', 'Automatique')], default='manual', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='known_addresses', to='discovery.chain')),
            ],
            options={
                'verbose_name_plural': 'known addresses',
                'constraints': [models.UniqueConstraint(fields=('chain', 'address'), name='wallets_unique_known', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='QualificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_txs_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('max_distinct_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('inactive_days', models.PositiveIntegerField(blank=True, null=True)),
                ('min_txs_active', models.PositiveIntegerField(blank=True, null=True)),
                ('history_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_mev_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('min_distinct_buys', models.PositiveIntegerField(blank=True, null=True)),
                ('min_portfolio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_portfolio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transfer_after_buy_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('follow_depth', models.PositiveIntegerField(blank=True, null=True)),
                ('funder_max_wallets', models.PositiveIntegerField(blank=True, null=True)),
                ('hot_wallet_min_counterparties', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_forward_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('deposit_forward_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('flipper_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('flipper_min_sold_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('flipper_min_share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('holder_min_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('accumulator_max_out_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('accumulator_min_positions', models.PositiveIntegerField(blank=True, null=True)),
                ('early_buyer_min_explosions', models.PositiveIntegerField(blank=True, null=True)),
                ('refilter_after_days', models.PositiveIntegerField(blank=True, null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualification_settings', to='discovery.chain')),
            ],
            options={
                'verbose_name': 'réglages de qualification',
                'verbose_name_plural': 'réglages de qualification',
                'constraints': [models.UniqueConstraint(fields=('chain',), name='wallets_one_settings_per_chain', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='TokenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('sold_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('sent_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('received_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('bought_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sold_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('buys', models.PositiveIntegerField(default=0)),
                ('sells', models.PositiveIntegerField(default=0)),
                ('first_at', models.DateTimeField()),
                ('last_at', models.DateTimeField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='discovery.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='discovery.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wallet', 'token'), name='wallets_unique_position')],
            },
        ),
        migrations.CreateModel(
            name='TokenTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente'), ('send', 'Envoi'), ('receive', 'Réception')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=78)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('counterparty', models.CharField(blank=True, default='', max_length=42)),
                ('block', models.PositiveBigIntegerField()),
                ('at', models.DateTimeField()),
                ('tx_hash', models.CharField(max_length=66)),
                ('log_index', models.PositiveIntegerField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='discovery.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='discovery.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'token', 'at'], name='wallets_trade_wallet_token')],
                'constraints': [models.UniqueConstraint(fields=('tx_hash', 'log_index', 'wallet'), name='wallets_unique_trade')],
            },
        ),
        migrations.CreateModel(
            name='WalletLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('transfer_after_buy', 'Transfert après achat'), ('funding', 'Financement initial')], max_length=24)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='discovery.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='discovery.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_wallet', 'to_wallet', 'kind'), name='wallets_unique_link')],
            },
        ),
        migrations.CreateModel(
            name='WalletProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('early_buyer', 'Early buyer'), ('linked', 'Wallet lié')], default='early_buyer', max_length=16)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('chains', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('prefiltered', 'Pré-filtré'), ('history_fetched', 'Historique récupéré'), ('qualified', 'Qualifié'), ('filtered', 'Écarté')], default='pending', max_length=24)),
                ('filter_reason', models.CharField(blank=True, default='', max_length=64)),
                ('portfolio_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('next_analysis_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='wallets.entity')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='discovery.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_analysis_at'], name='wallets_profile_status'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='wallets_profile_tags')],
            },
        ),
    ]
