# Generated by Django 5.2.17 on 2026-09-27 12:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_pipeline_v2'),
        ('wallets', '0003_reset_v1_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zerion_id', models.CharField(max_length=64)),
                ('chain', models.CharField(max_length=64)),
                ('tx_hash', models.CharField(max_length=66)),
                ('block', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mined_at', models.DateTimeField()),
                ('operation_type', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('fee_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('raw', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyPrice',
        ),
        migrations.RemoveField(
            model_name='walletprofile',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='tokenposition',
            name='token',
        ),
        migrations.RemoveField(
            model_name='tokenposition',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='tokentrade',
            name='token',
        ),
        migrations.RemoveField(
            model_name='tokentrade',
            name='wallet',
        ),
        migrations.RemoveIndex(
            model_name='walletprofile',
            name='wallets_profile_status',
        ),
        migrations.RemoveField(
            model_name='qualificationsettings',
            name='follow_depth',
        ),
        migrations.RemoveField(
            model_name='qualificationsettings',
            name='funder_max_wallets',
        ),
        migrations.RemoveField(
            model_name='walletprofile',
            name='chains',
        ),
        migrations.AddField(
            model_name='qualificationsettings',
            name='big_receive_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='active_chains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='history_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='history_cursor',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='last_mined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='linked_value_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='priority',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='walletlink',
            name='kind',
            field=models.CharField(choices=[('transfer_after_buy', 'Transfert après achat'), ('big_receive', 'Gros transfert reçu'), ('funding', 'Financement initial (information)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='walletprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('prefiltered', 'Pré-filtré (historique en cours)'), ('history_fetched', 'Historique complet'), ('qualified', 'Qualifié'), ('valued', 'Wallet lié valorisé'), ('filtered', 'Écarté')], default='pending', max_length=24),
        ),
        migrations.AddIndex(
            model_name='walletprofile',
            index=models.Index(fields=['status', 'priority'], name='wallets_profile_status_prio'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='discovery.wallet'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='TokenPosition',
        ),
        migrations.DeleteModel(
            name='TokenTrade',
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'mined_at'], name='wallets_tx_wallet_date'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'zerion_id'), name='wallets_unique_transaction'),
        ),
    ]
