# Generated by Django 5.2.17 on 2026-09-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_pipeline_v2'),
        ('wallets', '0004_drop_v1_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=64)),
                ('token_address', models.CharField(max_length=66)),
                ('token_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('bought_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('sold_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('sent_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('received_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('bought_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sold_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('buys', models.PositiveIntegerField(default=0)),
                ('sells', models.PositiveIntegerField(default=0)),
                ('first_at', models.DateTimeField()),
                ('last_at', models.DateTimeField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='discovery.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wallet', 'chain', 'token_address'), name='wallets_unique_position')],
            },
        ),
        migrations.CreateModel(
            name='TokenTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_index', models.PositiveSmallIntegerField()),
                ('chain', models.CharField(max_length=64)),
                ('token_address', models.CharField(max_length=66)),
                ('token_symbol', models.CharField(blank=True, default='', max_length=64)),
                ('token_decimals', models.PositiveSmallIntegerField(default=0)),
                ('fungible_id', models.CharField(blank=True, default='', max_length=100)),
                ('kind', models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente'), ('send', 'Envoi'), ('receive', 'Réception')], max_length=8)),
                ('direction', models.CharField(max_length=4)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=60)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=78)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('counterparty', models.CharField(blank=True, default='', max_length=42)),
                ('block', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mined_at', models.DateTimeField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='wallets.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='discovery.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'chain', 'token_address', 'mined_at'], name='wallets_trade_token')],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'transfer_index'), name='wallets_unique_transfer')],
            },
        ),
    ]
