# Generated by Django 5.2.17 on 2026-09-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0012_entities'),
        ('wallets', '0006_v2_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentrade',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Mouvement entre deux wallets de la même entité.'),
        ),
        migrations.AddField(
            model_name='walletlink',
            name='rejected',
            field=models.BooleanField(default=False, help_text="Rattachement refusé dans l'admin : jamais recréé."),
        ),
        migrations.AddField(
            model_name='walletlink',
            name='source',
            field=models.CharField(choices=[('hypersync', 'HyperSync'), ('zerion', 'Zerion')], default='zerion', max_length=16),
        ),
        migrations.AlterField(
            model_name='walletlink',
            name='kind',
            field=models.CharField(choices=[('transfer_after_buy', 'Transfert après achat'), ('big_receive', 'Gros transfert reçu'), ('transfer_to_vault', 'Transfert vers un coffre (on-chain)'), ('funding', 'Financement initial (information)')], max_length=24),
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField()),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='discovery.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=64)),
                ('token_address', models.CharField(max_length=66)),
                ('fungible_id', models.CharField(blank=True, default='', max_length=100)),
                ('symbol', models.CharField(blank=True, default='', max_length=64)),
                ('position_type', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=60)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='wallets.portfoliosnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='TokenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=66)),
                ('fungible_id', models.CharField(blank=True, default='', max_length=100)),
                ('symbol', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('decimals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_supply', models.DecimalField(blank=True, decimal_places=18, max_digits=60, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=18, max_digits=60, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chain', 'address'), name='wallets_unique_token_info')],
            },
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['wallet', 'fetched_at'], name='wallets_portfolio_date'),
        ),
    ]
