# Generated by Django 5.2.17 on 2026-09-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('candidate', 'Candidat'), ('analyzed', 'Analysé'), ('waiting_confirmation', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('buyers_extracted', 'Acheteurs extraits'), ('rejected', 'Rejeté')], default='candidate', max_length=32)),
                ('sources', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gt_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('evm_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('zerion_id', models.CharField(blank=True, default='', max_length=64)),
                ('hypersync_supported', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['gt_id'],
            },
        ),
        migrations.CreateModel(
            name='PipelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_pages', models.PositiveSmallIntegerField(default=10)),
                ('volume_pages_per_chain', models.PositiveSmallIntegerField(default=3)),
                ('candidate_cooldown_hours', models.PositiveIntegerField(default=72)),
                ('max_transfers_per_token', models.PositiveIntegerField(default=500000)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('gecko_requests_per_min', models.PositiveIntegerField(default=30)),
                ('hypersync_requests_per_min', models.PositiveIntegerField(default=60)),
                ('http_timeout_seconds', models.PositiveIntegerField(default=15)),
                ('http_max_retries', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'réglages du pipeline',
                'verbose_name_plural': 'réglages du pipeline',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Explosion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_block', models.PositiveBigIntegerField()),
                ('low_at', models.DateTimeField()),
                ('peak_block', models.PositiveBigIntegerField()),
                ('peak_at', models.DateTimeField()),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retention_pct', models.DecimalField(decimal_places=2, max_digits=7)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explosion', to='discovery.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=66)),
                ('symbol', models.CharField(blank=True, max_length=64)),
                ('decimals', models.PositiveSmallIntegerField(default=18)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='discovery.chain')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=66)),
                ('created_block', models.PositiveBigIntegerField(blank=True, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='discovery.token')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='discovery.token'),
        ),
        migrations.CreateModel(
            name='EarlyBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_buy_block', models.PositiveBigIntegerField()),
                ('first_buy_at', models.DateTimeField()),
                ('bought_amount', models.DecimalField(decimal_places=0, max_digits=78)),
                ('bought_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sold_amount', models.DecimalField(decimal_places=0, default=0, max_digits=78)),
                ('is_sniper', models.BooleanField(default=False)),
                ('explosion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='discovery.explosion')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_buys', to='discovery.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_change_24h_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_liquidity_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('min_volume_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('peak_volume_window_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('min_fdv_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_fdv_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_pool_age_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('min_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_retention_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('confirmation_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('confirmation_timeout_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('sniper_blocks', models.PositiveIntegerField(blank=True, null=True)),
                ('min_buy_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_buyers', models.PositiveIntegerField(blank=True, help_text='0 = pas de plafond. Vide = valeur globale.', null=True)),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_settings', to='discovery.chain')),
            ],
            options={
                'verbose_name': 'réglages de détection',
                'verbose_name_plural': 'réglages de détection',
                'constraints': [models.UniqueConstraint(fields=('chain',), name='discovery_one_settings_per_chain', nulls_distinct=False)],
            },
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('chain', 'address'), name='discovery_unique_token'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('token', 'address'), name='discovery_unique_pool'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', 'next_check_at'], name='discovery_cand_status_check'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('rejected', 'buyers_extracted')), _negated=True), fields=('token',), name='discovery_one_open_candidate'),
        ),
        migrations.AddConstraint(
            model_name='earlybuyer',
            constraint=models.UniqueConstraint(fields=('explosion', 'wallet'), name='discovery_one_buyer_per_explosion'),
        ),
    ]
