# Generated by Django 5.2.17 on 2026-09-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesettings',
            name='http_backoff_seconds',
            field=models.PositiveIntegerField(default=5, help_text='Attente avant la 1re nouvelle tentative, doublée à chaque essai.'),
        ),
    ]
