# Generated by Django 5.2.17 on 2026-09-26 21:12

from django.db import migrations, models


def set_global_window(apps, schema_editor):
    DetectionSettings = apps.get_model("discovery", "DetectionSettings")
    DetectionSettings.objects.filter(chain=None).update(explosion_window_hours=72)


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_pipeline_http_backoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionsettings',
            name='explosion_window_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Le point bas et le pic doivent se trouver dans ces dernières heures.', null=True),
        ),
        migrations.RunPython(set_global_window, migrations.RunPython.noop),
    ]
