# Generated by Django 5.2.17 on 2026-09-27 07:38

import apps.discovery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_explosion_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='native_fungible_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chain',
            name='rpc_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='chain',
            name='wrapped_fungible_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='extra_chains',
            field=models.JSONField(blank=True, default=list, help_text='gt_id des chaînes analysées en plus pour chaque wallet.'),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='qualification_batch_size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='stablecoin_symbols',
            field=models.JSONField(default=apps.discovery.models.default_stablecoins),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='zerion_daily_budget',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='zerion_requests_per_min',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
