# Generated by Django 5.2.17 on 2026-09-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_chain_rpc_and_qualification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='rpc_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
