# Generated by Django 5.2.17 on 2026-09-27 12:17

import apps.discovery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_chain_rpc_url_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinesettings',
            name='extra_chains',
        ),
        migrations.RemoveField(
            model_name='pipelinesettings',
            name='stablecoin_symbols',
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='history_refresh_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='prefilter_chains',
            field=models.JSONField(default=apps.discovery.models.default_prefilter_chains, help_text='gt_id des chaînes du pré-filtre HyperSync (+ la chaîne où le wallet est repéré).'),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='quote_symbols',
            field=models.JSONField(default=apps.discovery.models.default_quote_symbols, help_text='Monnaies de paiement : leurs jambes de trade ne comptent pas comme achats.'),
        ),
        migrations.AlterField(
            model_name='pipelinesettings',
            name='zerion_daily_budget',
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.AlterField(
            model_name='pipelinesettings',
            name='zerion_requests_per_min',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
