# Generated by Django 5.2.17 on 2026-09-27 13:46

import apps.discovery.models
from django.db import migrations, models


def set_defaults(apps, schema_editor):
    apps.get_model("discovery", "DetectionSettings").objects.filter(chain=None).update(
        explosion_window_hours=168, maturity_hours=336, breakout_multiplier=2, buyer_window_hours=0
    )
    Explosion = apps.get_model("discovery", "Explosion")
    Explosion.objects.filter(retention_pct__isnull=False).update(retention_status="held")
    Explosion.objects.filter(candidate__status="buyers_extracted").update(
        extraction_status="complete"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_explosion_trough'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionsettings',
            name='confirmation_timeout_hours',
        ),
        migrations.AddField(
            model_name='detectionsettings',
            name='breakout_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Une vague précédente retombée coupe le creux si elle a dépassé ce multiple.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detectionsettings',
            name='buyer_window_hours',
            field=models.PositiveIntegerField(blank=True, help_text="Heures d'achat avant le creux. 0 = depuis le lancement.", null=True),
        ),
        migrations.AddField(
            model_name='detectionsettings',
            name='maturity_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Âge du token au creux à partir duquel une vague compte pleinement. 0 = pas de pondération.', null=True),
        ),
        migrations.AddField(
            model_name='explosion',
            name='extraction_status',
            field=models.CharField(blank=True, choices=[('complete', 'Complète'), ('partial', 'Partielle')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='explosion',
            name='peak_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='explosion',
            name='retention_status',
            field=models.CharField(choices=[('pending', 'À mesurer'), ('held', 'Tenue'), ('rug', 'Rug')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='explosion',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='rug_priority_weight',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text="Poids d'une explosion « rug » dans la priorité de qualification.", max_digits=4),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='sell_pass_batch_size',
            field=models.PositiveIntegerField(default=500, help_text="Adresses d'acheteurs par requête de la passe des ventes."),
        ),
        migrations.AlterField(
            model_name='detectionsettings',
            name='explosion_window_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Le pic doit se trouver dans ces dernières heures (ignoré pour un ajout manuel).', null=True),
        ),
        migrations.AlterField(
            model_name='explosion',
            name='retention_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinesettings',
            name='prefilter_chains',
            field=models.JSONField(default=apps.discovery.models.default_prefilter_chains, help_text='gt_id des chaînes du pré-filtre HyperSync (+ chaîne où le wallet est repéré).'),
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop),
    ]
