# Generated by Django 5.2.17 on 2026-09-27 14:34

from django.db import migrations, models


def set_defaults(apps, schema_editor):
    apps.get_model("discovery", "DetectionSettings").objects.filter(chain=None).update(
        min_score=5, max_multiplier=10_000
    )
    apps.get_model("discovery", "PipelineSettings").objects.update(
        max_transfers_per_token=2_000_000
    )


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_explosion_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionsettings',
            name='max_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Au-delà, la vague est une anomalie (pool vidé, prix ~0). 0 = pas de plafond.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='detectionsettings',
            name='min_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score minimum (multiplicateur × maturité) : écarte les pumps de lancement.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinesettings',
            name='max_transfers_per_token',
            field=models.PositiveIntegerField(default=2000000),
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop),
    ]
