# Generated by Django 5.2.17 on 2026-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0010_score_and_multiplier_caps'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlybuyer',
            name='held_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Tokens détenus au creux (achetés − revendus avant le creux).', max_digits=78),
        ),
        migrations.AddField(
            model_name='earlybuyer',
            name='held_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Position au creux, au prix du creux.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='detectionsettings',
            name='min_buy_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Position minimum détenue au creux ($) pour retenir un acheteur.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='earlybuyer',
            name='sold_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Tokens revendus pendant la montée (creux → pic).', max_digits=78),
        ),
    ]
