# Generated by Django 5.2.17 on 2026-09-27 16:52

import django.db.models.deletion
from django.db import migrations, models


def set_defaults(apps, schema_editor):
    apps.get_model("discovery", "DetectionSettings").objects.filter(chain=None).update(
        hub_min_senders=10, vault_follow_depth=2, bot_window_days=7, vault_min_pct=20
    )


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0011_earlybuyer_position_at_trough'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionsettings',
            name='bot_window_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Jours avant le creux sur lesquels on mesure l'activité bot.", null=True),
        ),
        migrations.AddField(
            model_name='detectionsettings',
            name='hub_min_senders',
            field=models.PositiveIntegerField(blank=True, help_text="Un destinataire alimenté par au moins autant d'expéditeurs est un hub (router, exchange) : lui envoyer = sortie.", null=True),
        ),
        migrations.AddField(
            model_name='detectionsettings',
            name='vault_follow_depth',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Niveaux de coffres suivis pendant la montée.', null=True),
        ),
        migrations.AddField(
            model_name='detectionsettings',
            name='vault_min_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Envoi minimum (% de ce que l'expéditeur a reçu) qui crée un coffre.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='earlybuyer',
            name='inherited_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=78),
        ),
        migrations.AddField(
            model_name='earlybuyer',
            name='inherited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='discovery.wallet'),
        ),
        migrations.AddField(
            model_name='earlybuyer',
            name='inherited_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de revient hérité.', max_digits=20),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='token_info_refresh_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='pipelinesettings',
            name='zerion_operation_types',
            field=models.CharField(default='trade,send,receive,execute,mint,burn,claim', help_text='Types de transactions Zerion récupérés (séparés par des virgules).', max_length=300),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed', to='discovery.entity')),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.AddField(
            model_name='earlybuyer',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_buys', to='discovery.entity'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='discovery.entity'),
        ),
        migrations.CreateModel(
            name='EntityEarlyBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_amount', models.DecimalField(decimal_places=0, max_digits=78)),
                ('held_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('first_buy_at', models.DateTimeField()),
                ('sold_during_rise_pct', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explosion_buys', to='discovery.entity')),
                ('explosion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_buys', to='discovery.explosion')),
            ],
            options={
                'ordering': ['explosion', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('entity', 'explosion'), name='discovery_one_entity_buy_per_explosion')],
            },
        ),
        migrations.CreateModel(
            name='ExcludedBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=32)),
                ('txs_per_day', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('held_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('explosion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded', to='discovery.explosion')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='discovery.wallet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('explosion', 'wallet'), name='discovery_one_exclusion_per_explosion')],
            },
        ),
        migrations.CreateModel(
            name='TokenTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66)),
                ('log_index', models.PositiveIntegerField()),
                ('block', models.PositiveBigIntegerField()),
                ('at', models.DateTimeField()),
                ('tx_from', models.CharField(max_length=42)),
                ('sender', models.CharField(max_length=42)),
                ('recipient', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=78)),
                ('kind', models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente'), ('exit', 'Sortie'), ('internal', "Interne à l'entité"), ('vault', 'Vers un nouveau coffre'), ('receive', 'Réception')], max_length=16)),
                ('explosion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='discovery.explosion')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='discovery.token')),
            ],
            options={
                'indexes': [models.Index(fields=['explosion', 'sender'], name='discovery_transfer_sender')],
                'constraints': [models.UniqueConstraint(fields=('token', 'tx_hash', 'log_index'), name='discovery_unique_token_transfer')],
            },
        ),
        migrations.RunPython(set_defaults, migrations.RunPython.noop),
    ]
