# Generated by Django 5.2.17 on 2026-09-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0012_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionsettings',
            name='bot_window_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Jours récents sur lesquels on mesure l'activité (tx signées/jour).", null=True),
        ),
    ]
