# Generated by Django 5.2.17 on 2026-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0013_alter_detectionsettings_bot_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinesettings',
            name='hypersync_timeout_seconds',
            field=models.PositiveIntegerField(default=30, help_text="Délai max d'une requête HyperSync avant nouvelle tentative."),
        ),
    ]
