# Generated by Django 5.0.1 on 2026-05-31 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=20)),
                ('total_portfolio_value', models.FloatField(blank=True, null=True)),
                ('is_smart_wallet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallets',
                'ordering': ['-total_portfolio_value'],
            },
        ),
        migrations.CreateModel(
            name='SmartWallet',
            fields=[
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='smart_wallet_data', serialize=False, to='wallets.wallet')),
                ('optimal_threshold_tier', models.IntegerField()),
                ('quality_score', models.FloatField()),
                ('threshold_status', models.CharField(max_length=20)),
                ('optimal_roi', models.FloatField()),
                ('optimal_winrate', models.FloatField()),
                ('global_roi', models.FloatField()),
                ('global_winrate', models.FloatField()),
            ],
            options={
                'db_table': 'smart_wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletQualified',
            fields=[
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='qualification', serialize=False, to='wallets.wallet')),
                ('final_score', models.FloatField()),
                ('classification', models.CharField(max_length=20)),
                ('weighted_roi', models.FloatField()),
                ('taux_reussite', models.FloatField()),
                ('nb_trades', models.IntegerField()),
            ],
            options={
                'db_table': 'wallet_qualified',
            },
        ),
        migrations.CreateModel(
            name='ConsensusSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=50)),
                ('contract_address', models.CharField(max_length=42)),
                ('chain', models.CharField(max_length=50)),
                ('nb_wallets', models.IntegerField()),
                ('total_usd_invested', models.FloatField()),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('wallets', models.ManyToManyField(related_name='consensus_signals', to='wallets.wallet')),
            ],
            options={
                'db_table': 'consensus_signals',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletBrute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('token_address', models.CharField(max_length=42)),
                ('contract_address', models.CharField(max_length=42)),
                ('chain', models.CharField(max_length=50)),
                ('temporality', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'wallet_brute',
                'unique_together': {('wallet_address', 'token_address', 'temporality')},
            },
        ),
        migrations.CreateModel(
            name='WalletPositionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('fungible_id', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=42)),
                ('change_type', models.CharField(max_length=20)),
                ('old_amount', models.FloatField()),
                ('new_amount', models.FloatField()),
                ('usd_change', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_changes', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_position_changes',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fungible_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('contract_address', models.CharField(max_length=42)),
                ('chain', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('usd_value', models.FloatField()),
                ('in_portfolio', models.BooleanField(default=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='wallets.wallet')),
            ],
            options={
                'db_table': 'tokens',
                'ordering': ['-usd_value'],
                'unique_together': {('wallet', 'fungible_id')},
            },
        ),
        migrations.CreateModel(
            name='TokenAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_symbol', models.CharField(max_length=50)),
                ('total_invested', models.FloatField()),
                ('total_realized', models.FloatField()),
                ('roi_percentage', models.FloatField()),
                ('is_winning', models.BooleanField()),
                ('status', models.CharField(max_length=20)),
                ('holding_days', models.IntegerField(default=0)),
                ('in_portfolio', models.BooleanField(default=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_analytics', to='wallets.wallet')),
            ],
            options={
                'db_table': 'token_analytics',
                'indexes': [models.Index(fields=['wallet', 'roi_percentage'], name='token_analy_wallet__9618a1_idx')],
                'unique_together': {('wallet', 'token_symbol')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fungible_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('hash', models.CharField(max_length=66)),
                ('date', models.DateTimeField()),
                ('operation_type', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=20)),
                ('swap_description', models.TextField(blank=True)),
                ('contract_address', models.CharField(max_length=42)),
                ('quantity', models.FloatField()),
                ('price_per_token', models.FloatField()),
                ('total_value_usd', models.FloatField()),
                ('direction', models.CharField(max_length=10)),
                ('recipient_address', models.CharField(blank=True, max_length=42)),
                ('sender_address', models.CharField(blank=True, max_length=42)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'transaction_history',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['wallet', 'date'], name='transaction_wallet__2e5ecd_idx'), models.Index(fields=['fungible_id'], name='transaction_fungibl_90e0f4_idx')],
                'unique_together': {('wallet', 'hash')},
            },
        ),
        migrations.CreateModel(
            name='WalletTierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_usd', models.IntegerField()),
                ('roi_percentage', models.FloatField()),
                ('winrate', models.FloatField()),
                ('nb_trades', models.IntegerField()),
                ('nb_gagnants', models.IntegerField()),
                ('is_optimal_tier', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_performance', to='wallets.wallet')),
            ],
            options={
                'db_table': 'wallet_tier_performance',
                'unique_together': {('wallet', 'tier_usd')},
            },
        ),
    ]
