# Generated by Django 5.0.1 on 2026-05-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='contract_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contract_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='walletpositionchange',
            name='contract_address',
            field=models.CharField(max_length=100),
        ),
    ]
