# Generated by Django 5.0.1 on 2026-05-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_token_contract_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Pipeline Control Panel',
                'verbose_name_plural': 'Pipeline Control Panel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExplosiveToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('token_address', models.CharField(max_length=100)),
                ('chain', models.CharField(max_length=50)),
                ('pool_address', models.CharField(blank=True, max_length=100, null=True)),
                ('pool_age_hours', models.FloatField(blank=True, null=True)),
                ('price_change_24h', models.FloatField(blank=True, null=True)),
                ('volume_24h', models.FloatField(blank=True, null=True)),
                ('liquidity_usd', models.FloatField(blank=True, null=True)),
                ('fdv', models.FloatField(blank=True, null=True)),
                ('buys_ratio', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('explosion_start_date', models.DateTimeField(blank=True, null=True)),
                ('explosion_peak_date', models.DateTimeField(blank=True, null=True)),
                ('explosion_pct', models.FloatField(blank=True, null=True)),
                ('hours_gap', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('hours_since_now', models.FloatField(blank=True, null=True)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'explosive_tokens_detected',
                'indexes': [models.Index(fields=['chain'], name='explosive_t_chain_edebce_idx'), models.Index(fields=['detected_at'], name='explosive_t_detecte_6bc083_idx'), models.Index(fields=['traite'], name='explosive_t_traite_69589d_idx')],
                'unique_together': {('token_address', 'chain')},
            },
        ),
        migrations.CreateModel(
            name='TokenPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.CharField(max_length=100)),
                ('chain', models.CharField(max_length=50)),
                ('pool_address', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'token_explosif_history_prices',
                'indexes': [models.Index(fields=['token_address', 'chain'], name='token_explo_token_a_5327c9_idx'), models.Index(fields=['date'], name='token_explo_date_1a2466_idx')],
                'unique_together': {('token_address', 'chain', 'date')},
            },
        ),
    ]
